# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 770205daa36c2e4363cd7b044c283ae6a72b0577616c220ff0cb0e6690b9943a01f9c554a6ad8bceae20f01bc65b27ac71cab6eafcbe3c97039cd2abc085b144

test:
  secret_key_base: 7dbf0b34c49a7c45bc5188683124939f98dcfc9b9380bcc65e761f706aaff8b523c4bd6634e5627313bbba3d52d5144fb3d276a38e81b77e226466e11659566c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
